/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 modelDraco.gltf --transform 
Files: modelDraco.gltf [112.14MB] > /Users/zoya/Desktop/gaming_room/modelDraco-transformed.glb [6.19MB] (94%)
Author: Shabeer Ahmed (https://sketchfab.com/shabeer113ahmed)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-room-64c205b5c47c47f4b9c930da182b0f0f
Title: Gaming room,
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function GamingRoomModel(props) {
  const { nodes, materials } = useGLTF("/gamin.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.plastic}
        position={[-3.887, 3.837, 1.136]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.267, 0.119, 0.267]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.screen}
        position={[-3.887, 3.837, 1.136]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.267, 0.119, 0.267]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Plastic}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.ShinyPlastic}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.LeatherCougar2}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.LeatherCougar}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.PaletteMaterial001}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.Leather}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials["Leather.001"]}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials["Leather.002"]}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.Belt}
        position={[-1.749, 1.208, 2.171]}
        rotation={[-Math.PI, -0.789, -Math.PI]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials["6_Degrees"]}
        position={[-6.491, 2.627, 1.547]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.074}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials["9_Degrees"]}
        position={[-6.491, 2.627, 1.547]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.074}
      />
      <mesh
        geometry={nodes.Object_35.geometry}
        material={materials.Stabilizers}
        position={[-6.491, 2.627, 1.547]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.074}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.Keycaps}
        position={[-6.491, 2.627, 1.547]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.074}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.material}
        position={[-6.491, 2.627, 1.547]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.074}
      />
      <mesh
        geometry={nodes.Object_39.geometry}
        material={materials.Wire}
        position={[-6.491, 2.627, 1.547]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.074}
      />
      <mesh
        geometry={nodes.Object_90.geometry}
        material={materials.aiStandardSurface3SG}
        position={[-3.378, 2.829, 1.255]}
        scale={0.341}
      />
      <mesh
        geometry={nodes.Object_92.geometry}
        material={materials.aiStandardSurface2SG}
        position={[-3.378, 2.829, 1.255]}
        scale={0.341}
      />
      <mesh
        geometry={nodes.Object_93.geometry}
        material={materials.aiStandardSurface1SG}
        position={[-3.378, 2.829, 1.255]}
        scale={0.341}
      />
      <mesh
        geometry={nodes.Object_117.geometry}
        material={materials.PaletteMaterial002}
        scale={3.856}
      />
      <mesh
        geometry={nodes.Object_119.geometry}
        material={materials.PaletteMaterial003}
        scale={3.856}
      />
      <mesh
        geometry={nodes.Object_121.geometry}
        material={materials["Material.004"]}
        position={[-1.838, 2.456, 3.846]}
        scale={[1, 1, 2.57]}
      />
      <mesh
        geometry={nodes.Object_137.geometry}
        material={materials.PaletteMaterial004}
        position={[0.148, 6.84, 0.206]}
        scale={3.295}
      />
      <mesh
        geometry={nodes.Object_139.geometry}
        material={materials.PaletteMaterial005}
        scale={3.856}
      />
    </group>
  );
}

useGLTF.preload("/gamin.glb");
